[package]
name = "medieval-realms-server"
version = "0.1.0"
authors = ["Jon Jekeli <jon@marxent.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "*"
json = "*"
uuid = { version = "*", features = ["v4"] }
